### ISSUE TITLE
Issues with actions on package with sf dependency

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/tic#244]
`tic` is a great package for auto-deploy. I hope reporting my experience will help improve it further.

Experience: after running the following command in a [small package with `sf` Suggests dependency](https://github.com/ITSLeeds/od):

```r
tic::use_tic(wizard = FALSE, linux = "ghactions", mac = "none", windows = "none", deploy = "ghactions", matrix = "ghactions")
```

![image](https://user-images.githubusercontent.com/1825120/78992139-7a614e00-7b32-11ea-83f3-c4010af4e2e4.png)

Many of the actions failed. I was surprised to see Windows and Mac actions after setting them to `none` above.

Specific issues I found:

- [ ] On Mac (which I'm not too worried about which I plan to turn-off but reporting in case it's of use) it said `ERROR: dependency ‘memoise’ is not available for package ‘tic’`  https://github.com/ITSLeeds/od/runs/576793655#step:15:333
- [ ] On Ubuntu there it does not install sf: https://github.com/ITSLeeds/od/runs/576793666#step:16:103 - fixed using `sysreqs` package
- [ ] Builds on ubuntu-latest (devel) seem to fail before they even get started: https://github.com/ITSLeeds/od/runs/576858671
- [x] On Windows it passes :tada:  even though I asked it not to build on Windows!

I know various things are in flux so am not expecting a quick fix. Hope this experience is of use/interest to others.

**Comment by Robinlovelace** [comment]
One question: is it worth making use of https://github.com/r-hub/sysreqs to help with system deps?

**Comment by Robinlovelace** [comment]
Good news: I could fix the Ubuntu build fairly easily with [these lines](https://github.com/ITSLeeds/od/pull/15/commits/6b918c32b9bd102b5617eb082e57dfcefd076915):

```
      - name: sf and system libraries
        if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          # sudo apt install libudunits2-dev
          # libproj-dev libgeos-dev libgdal-dev
          # sudo R -e "install.packages('sf')"
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
```

Only tricky thing is knowing which ppa to add, but that problem will disappear with the release of Ubuntu 20.04 so may not be worth fixing. The other points may be though, impressive that sysreqs can install the right dependencies.

**Comment by Robinlovelace** [comment]
Another update: builds on ubuntu-latest (devel) seem to fail before they even get started: https://github.com/ITSLeeds/od/runs/576858671

Will document that in the opening comment.

**Comment by pat-s** [comment]
> Many of the actions failed. I was surprised to see Windows and Mac actions after setting them to none above.

For actions you always get the full matrix since there is only one template (yet). I haven't yet had time to adjust this to work nicely with `use_tic()`.

> One question: is it worth making use of r-hub/sysreqs to help with system deps?

I'd like to use it but right now its very outdated and only works on Linux (somewhat). Therefore it is not included in the default template.

>  builds on ubuntu-latest (devel) seem to fail before they even get started: ubuntu-latest (devel) 

See https://github.com/r-lib/actions/issues/49.

> On Mac (which I'm not too worried about which I plan to turn-off but reporting in case it's of use)

Mac-devel builds are broken atm because of issues when installing {digest}, you can see these in the log.

> Good news: I could fix the Ubuntu build fairly easily with these lines:

I don't think a ppa is needed.
However, spatial libs are (and never will be) part of the default library stack. 
See https://docs.ropensci.org/tic/articles/ci-providers.html#spatial-libraries-gdal-proj-geos

**Comment by Robinlovelace** [comment]
Thanks for the quickfire response, happy with that and it sounds like you're already tracking the issues that are actually issues so closing for now.

> I don't think a ppa is needed.

I think you do on Ubuntu 18.04, which is, for the next month at least, the default version that ghactions will build on and this could be the case until summer when the point release of Ubuntu 20.04 is released, as documented here: https://geocompr.github.io/post/2020/installing-r-spatial-ubuntu/

**Comment by pat-s** [comment]
{sf} has the following minimum reqs 

> For Unix-alikes, GDAL (>= 2.0.1), GEOS (>= 3.4.0) and Proj.4 (>= 4.8.0) are required.

bionic comes with 

- gdal 2.2.3
- proj 4.9.3
- geos 3.6.2

Why is a ppa needed?
On my 18.04 box {sf} v9.1 installs just fine with these system libs.

**Comment by Robinlovelace** [comment]
Reproducible example illustrating the point:

```sh
docker run -it rocker/r-ubuntu:18.04 /bin/bash
R
install.packages("sf")
```

**Comment by Robinlovelace** [comment]
Larger reprex that finally should succeed:

```
docker run -it rocker/r-ubuntu:18.04 /bin/bash
Rscript -e "install.packages('remotes')"
Rscript -e "remotes::install_github('r-hub/sysreqs')"
wget https://github.com/r-spatial/sf/raw/master/DESCRIPTION
sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION', 'linux-x86_64-ubuntu-gcc'))")
eval "$sysreqs"
# E: Unable to locate package libudunits2-dev
R
install.packages("sf")
q()
n

add-apt-repository ppa:ubuntugis/ppa

sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION', 'linux-x86_64-ubuntu-gcc'))")
eval "$sysreqs"

apt install libudunits2-dev

```

**Comment by Robinlovelace** [comment]
Retesting it, may be working without the repos...

**Comment by pat-s** [comment]
`libudunits2-dev` is in the `universe` [repo](https://packages.ubuntu.com/bionic/libudunits2-dev) which may not be activated in the `r-ubuntu` image. I'd say that this is a shortcoming there and even if that would prevent the install, its easier to enable the `universe` repo than adding a ppa and installing multiple formulas from it.
Especially because the `universe` repo is always enabled by default on a normal 18.04 installation and its nice if ppas can be avoided.

**Comment by Robinlovelace** [comment]
Seems like it's working in any case, try this:

```bash
docker run --rm -it rocker/r-ubuntu:18.04 /bin/bash
Rscript -e "install.packages('remotes')"
Rscript -e "remotes::install_github('r-hub/sysreqs')"
wget https://github.com/r-spatial/sf/raw/master/DESCRIPTION
sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION', 'linux-x86_64-ubuntu-gcc'))")
eval "$sysreqs"

R
install.packages("sf")
```

**Comment by Robinlovelace** [comment]
Interestingly, using the instructions from the `sf` README it fails:

```
docker run --rm -it rocker/r-ubuntu:18.04 /bin/bash

# manually
sudo apt install libudunits2-dev libgdal-dev libgeos-dev libproj-dev

R
install.packages("sf")

```

With:

```
configure: error:
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
```

Heads-up @edzer I plan to put in a PR for this, not sure if it's an 18.04 specific issue yet with the instructions.

**Comment by edzer** [comment]
I followed the instructions for ubuntu in the README, modified them to work with docker (omit `sudo`), and was successful:
```
> library(sf)
Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
```
Did you add the ubuntugis ppa?

**Comment by pat-s** [comment]
> Seems like it's working in any case, try this:

Works just fine for me.

Also 

```
echo $sysreqs

 apt-get -y update && apt-get install -y libgeos-dev libgeos++-dev gdal-bin libgdal-dev libudunits2-dev pandoc pandoc-citeproc git-core make unixodbc-dev libproj-dev libpq-dev libpng-dev imagemagick libssl-dev libcurl4-openssl-dev libxml2-dev libcairo2-dev
```

included `libudunits2-dev`. All fine?

**Comment by pat-s** [comment]
> manually
> sudo apt install libudunits2-dev libgdal-dev libgeos-dev libproj-dev

This should be

```sh
apt-get -y update && apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev
```

**Comment by Robinlovelace** [comment]
> Did you add the ubuntugis ppa?

I tried both and, to my surprise, it seems `sf` can be installed without the ubuntugis ppa, as per this reproducible example:

```bash
docker run --rm -it rocker/r-ubuntu:18.04 /bin/bash

# manually - instructions from sf readme:
apt-get -y update apt-get install -y &&
  libudunits2-dev libgdal-dev libgeos-dev libproj-dev

# manually from sysreqs:
apt-get -y update apt-get install -y &&
  libgeos-dev libgeos++-dev \
  gdal-bin libgdal-dev libudunits2-dev make unixodbc-dev \
  libproj-dev libpq-dev libpng-dev imagemagick libssl-dev \
  libcurl4-openssl-dev libcairo2-dev libxml2-dev


R
install.packages("sf")
```

Feel free to give it a spin to verify

**Comment by pat-s** [comment]
> I tried both and, to my surprise, it seems sf can be installed without the ubuntugis ppa, as per this reproducible example:

Already did - see my last two comments.

Relieved I was right here 😅 

While it is not a bad thing to use the ubuntugis-ppa because you might get newer versions of the core libs, it adds additional (config) overhead for CI runs.
I think its nice to mention it but one should also say that it's optional (also within install guides).

For a long time (since gdal 2.0 was released) the ubuntugis-ppa was defacto required because the ubuntu core libs for their LTS releases did not ship gdal2.
However, since 18.04 this is resolved and AFAIK gdal2 was the only blocker in all of this. 

Focal comes with proj 6.3.1 and should also be fine in this regard, shouldn't it?

**Comment by edzer** [comment]
Without the ppa:
```
> library(sf)
Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
```
(which is pretty much what windows binary installs are still stuck with...)

But I still don't see what @Robinlovelace 's issue was.

**Comment by Robinlovelace** [comment]
My issue was that the README implies that the ubuntugis repo is needed for sf to install:

> Dependencies for recent (non-LTS, later than bionic) versions of Ubuntu are available in the official repositories; install them with

If it said

> non-LTS, later than and including bionic

it would be clear. I've opened a PR to make it clearer: https://github.com/r-spatial/sf/compare/master...Robinlovelace:patch-1

> Relieved I was right here sweat_smile

I stand corrected :+1:

**Comment by Robinlovelace** [comment]
Follow-up on this @pat-s which may be worthy of a new issue, is there a possibility of a convenience function to add necessary lines in the yaml file for sf and perhaps other packages? Seems a bit clunky and now that this is stabilising (touch wood!) I wonder if there could be a way of doing this with a function call. See here for very common step (I cannot even be sure this is correct): https://github.com/saferactive/traffiCalmr/commit/33d9054213eef6fabceda3fd6d03727f94386421

Happy to open a new issue if that would be useful.

**Comment by pat-s** [comment]
> Follow-up on this @pat-s which may be worthy of a new issue, is there a possibility of a convenience function to add necessary lines in the yaml file for sf and perhaps other packages? 

No, I do not think that package specific functions in {tic} (or any other package) are a good idea.
You can write your own personal helper function if you want to.
Remember that the order of the blocks is important.

Also, the content of this helper function is probably highly debatable (given the latest discussions in {sf} and r-spatial/discuss) and will not be static for a very long time.
In the shown file, I do not see the need for the ppa or the sysreqs part (if its only about the spatial libs).

**Comment by Robinlovelace** [comment]
Thanks for the feedback. I wonder if there the solution could be implemented in an action along the lines of the `r-lib/actions/setup-pandoc@v1` action: https://github.com/r-lib/actions/tree/master/setup-pandoc

**Comment by pat-s** [comment]
This would probably work and fit though creating a custom action requires writing Typescript (I guess) and might therefore be not that trivial.

**Comment by Robinlovelace** [comment]
I'll open an issue and see what happens...
